replicaCount: 1

containerPort: 3000

image:
  repository: rohitbondre1309/hello-world-app
  tag: 14
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30082