apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: rohitbondre1309/hello-world-app:fadb3eceeaf78a42da0e3f3e3dfa943a50405ddc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000